server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_gpt?serverTimezone=UTC
    username: root
    password: aiggie01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
